insert into public.ssd_products (
    name,
    brand,
    price,
    capacity_gb,
    technology,
    condition,
    warranty,
    affiliate_tag,
    featured,
    form_factor,
    image_url,
    amazon_url
) values
(
    'Orico 512GB SATA SSD',
    'Orico',
    79.99,
    512,
    'Internal M.2 SSD with B + M Key',
    'New',
    '5 years',
    'autohomegadge-20',
    'false',
    'M.2 2280',
    'https://m.media-amazon.com/images/I/61oSqrZ3P+L._AC_SL1500_.jpg',
    'https://a.co/d/0b7DMvyW'
),
(
    'Orico 4TB SATA SSD',
    'Orico',
    399.99,
    4096,
    'Internal M.2 SSD with B + M Key',
    'New',
    '5 years',
    'autohomegadge-20',
    'true',
    'M.2 2280',
    'https://m.media-amazon.com/images/I/61oSqrZ3P+L._AC_SL1500_.jpg',
    'https://a.co/d/04SMfjwP'
),
(
    'Dell 4TB 7.2K SAS',
    'Dell',
    81.99,
    4096,
    '7.2K SAS',
    'New',
    '5 years',
    'autohomegadge-20',
    'true',
    '3.5"',
    'https://images-na.ssl-images-amazon.com/images/I/61g4Gn7kRgL._AC_SL1500_.jpg',
    'https://a.co/d/05pHdXMM'
);